[versions]
androidGradleVersion = "7.4.2"
kotlinGradleVersion = "1.8.0"

core = "1.7.0"
appcompat = "1.4.1"
material = "1.5.0"
constraintLayout = "2.1.3"

junit = "4.13.2"
ext-junit = "1.1.5"
espresso-core = "3.5.1"

[libraries]

core-ktx = {module = "androidx.core:core-ktx",version.ref = "core"}
appcompat = {module = "androidx.appcompat:appcompat",version.ref = "appcompat"}
material = {module = "com.google.android.material:material",version.ref="material"}
constraint-layout = {module = "androidx.constraintlayout:constraintlayout",version.ref = "constraintLayout"}

junit = {module = "junit:junit",version.ref = "junit"}
ext-junit = {module = "androidx.test.ext:junit",version.ref = "ext-junit"}
espresso-core = {module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core"}
